version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: alper123
      MYSQL_DATABASE: crudusers
      MYSQL_USER: root
      MYSQL_PASSWORD: alper123
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbit-mq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: mongopassword
      MONGO_INITDB_DATABASE: notifications
    volumes:
      - mongo_data:/data/db

  rest:  # Student service
    build:
      context: ./rest
    container_name: student-service
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/crudusers
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: alper123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      SPRING_RABBITMQ_HOST: rabbit-mq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_DEFAULT_USER: guest
      SPRING_RABBITMQ_DEFAULT_PASS: guest
    depends_on:
      - mysql
      - redis
      - rabbitmq

  notification:  # Notification service
    build:
      context: ./notification
    container_name: notification-service
    ports:
      - "8081:8081"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongoadmin:mongopassword@mongo:27017/notification_db
      SPRING_RABBITMQ_HOST: rabbit-mq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_DEFAULT_USER: guest
      SPRING_RABBITMQ_DEFAULT_PASS: guest
    depends_on:
      - rabbitmq
      - mongo

volumes:
  mysql_data:
  mongo_data:
